server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Route for Auth Service
        - id: auth-service-route
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**

# Logging to track request flow
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.hotelgo.gateway: DEBUG
